server:
  port: 9006

spring:
  application:
    name: lexdata-synthese
  datasource:
    # On laisse Docker Compose écraser ça, mais on met des valeurs par défaut propres
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/lexdata_db}
    username: ${SPRING_DATASOURCE_USERNAME:lexdata_user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret_password}
    driver-class-name: org.postgresql.Driver
  
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    # Magie : Si Docker passe EUREKA_INSTANCE_HOSTNAME, on l'utilise. Sinon, localhost.
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: true
    # ON A SUPPRIMÉ ip-address: 127.0.0.1 !!!
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://admin:admin_password@localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.security: WARN
    org.springframework.web: WARN
    com.lexdata.synthese: INFO

springdoc:
  api-docs:
    path: /api/synthese/v3/api-docs
  swagger-ui:
    path: /api/synthese/swagger-ui.html

lexdata:
  app:
    jwtSecret: ${LEXDATA_JWT_SECRET}
    jwtExpirationMs: ${LEXDATA_JWT_EXPIRATION:86400000}
  juridique-base-url: ${JURIDIQUE_BASE_URL:http://localhost:9101}

