package com.lexdata.user.models;

public enum LegalDomain {
    DROIT_DES_AFFAIRES,
    DROIT_PENAL,
    DROIT_CIVIL,
    DROIT_SOCIAL_ET_TRAVAIL,
    DROIT_IMMOBILIER_ET_FONCIER,
    FISCALITE_ET_DOUANES,
    DROIT_PUBLIC_ET_ADMINISTRATIF,
    PROPRIETE_INTELLECTUELLE,
    DROIT_ENVIRONNEMENTAL,
    DROIT_INTERNATIONAL,
    DROIT_NUMERIQUE_ET_DONNEES
}
