---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lexdata-gateway-hpa
  namespace: lexdata
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lexdata-gateway
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lexdata-auth-hpa
  namespace: lexdata
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lexdata-auth
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lexdata-user-hpa
  namespace: lexdata
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lexdata-user
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

