server:
  port: 9012

spring:
  application:
    name: lexdata-paiements
  datasource:
    url: jdbc:postgresql://localhost:5432/lexdata_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin_password@lexdata-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

lexdata:
  jwtSecret: "votre_cle_secrete_tres_longue_et_securisee_pour_lexdata_auth_service"
  jwtExpirationMs: 1800000
