---
# ===========================================================================
# Kibana — Deployment + Service
# ===========================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexdata-kibana
  namespace: lexdata
  labels:
    app: lexdata-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lexdata-kibana
  template:
    metadata:
      labels:
        app: lexdata-kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.17.10
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://lexdata-elasticsearch:9200"
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: lexdata-kibana
  namespace: lexdata
spec:
  selector:
    app: lexdata-kibana
  ports:
    - port: 5601
      targetPort: 5601
